"""Synthetic sales-lead dataset generation.

Models a B2B aerospace/defense sales pipeline (loosely: helicopter fleet
deals)
with realistic, imperfect signal: features that correlate with deal
outcome but don't determine it perfectly, some noisy/contradictory leads,
and missing data on some fields (mirroring a real, imperfectly-maintained
CRM rather than a clean synthetic set).

The data is entirely synthetic, generated by this script; it is not any
real company's CRM data.
"""
import random
from dataclasses import dataclass, field
from typing import Optional

INDUSTRIES = ["Defense", "EMS/Rescue", "Offshore", "VIP/Corporate", "Utility", "Law Enforcement"]
REGIONS = ["DACH", "Nordics", "Southern Europe", "Middle East", "Asia-Pacific", "North America"]
LEAD_SOURCES = ["Trade Show", "Referral", "Inbound Web", "Cold Outreach", "Government Tender", "Partner Channel"]


@dataclass
class Lead:
    lead_id: int
    industry: str
    region: str
    lead_source: str
    fleet_size_estimate: Optional[int]     # how many aircraft the prospect operates; None = unknown
    budget_confirmed: bool
    engaged_last_90_days: bool
    prior_customer: bool
    num_touchpoints: int
    competitor_incumbent: Optional[str]    # None if greenfield / unknown
    won: int                               # 1 = deal won, 0 = lost/no-decision (label)


def _decide_outcome(rng, industry, fleet_size, budget_confirmed, engaged, prior_customer,
                     touchpoints, competitor_incumbent):
    """Assigns a win probability from realistic-but-imperfect signal, then
    samples the outcome. No single feature determines the result — this
    mirrors real sales data where the signal is genuinely noisy, not a
    deterministic rule in disguise.
    """
    score = 0.12  # base rate

    if budget_confirmed:
        score += 0.22
    if engaged:
        score += 0.14
    if prior_customer:
        score += 0.20
    if fleet_size is not None and fleet_size >= 15:
        score += 0.10
    if touchpoints >= 5:
        score += 0.08
    elif touchpoints <= 1:
        score -= 0.05
    if competitor_incumbent is None:
        score += 0.06  # greenfield slightly easier than displacing an incumbent
    if industry in ("Defense", "Government Tender"):
        score -= 0.04  # longer, harder cycles

    # noise: real deals are won/lost for reasons not in the CRM at all
    score += rng.gauss(0, 0.12)
    score = max(0.02, min(0.92, score))
    return 1 if rng.random() < score else 0


def generate_leads(n=900, seed=42):
    rng = random.Random(seed)
    leads = []
    for i in range(n):
        industry = rng.choice(INDUSTRIES)
        region = rng.choice(REGIONS)
        source = rng.choice(LEAD_SOURCES)

        # ~12% of leads have no fleet size on file (missing CRM data)
        fleet_size = None if rng.random() < 0.12 else rng.randint(1, 60)

        budget_confirmed = rng.random() < 0.35
        engaged = rng.random() < 0.55
        prior_customer = rng.random() < 0.18
        touchpoints = max(0, int(rng.gauss(4, 2.5)))
        competitor_incumbent = None if rng.random() < 0.45 else rng.choice(
            ["Leonardo", "Bell", "Sikorsky", "MD Helicopters"]
        )

        won = _decide_outcome(
            rng, industry, fleet_size, budget_confirmed, engaged,
            prior_customer, touchpoints, competitor_incumbent
        )

        leads.append(Lead(
            lead_id=i,
            industry=industry,
            region=region,
            lead_source=source,
            fleet_size_estimate=fleet_size,
            budget_confirmed=budget_confirmed,
            engaged_last_90_days=engaged,
            prior_customer=prior_customer,
            num_touchpoints=touchpoints,
            competitor_incumbent=competitor_incumbent,
            won=won,
        ))
    return leads
